### ISSUE TITLE
自定义Convertor 数据缺少最后一个字符。

### ISSUE THREAD

**Issue by Zbuter** [dromara/TLog#2]
包括页面文档在内，在使用自定义convertor的时候 。
除空字符串外 无论convert方法返回什么字符串 在日志打印中都缺少最后一个字符。
不太清楚这样设计的原因。 
但日志打印内容并不是想要的内容。
现在为了达到想要的效果每次只能在后面拼接一个多余的字符才能解决。

**Comment by jdklog** [comment]
看看源码就知道了，

AspectLogAop这个类,
79行:

aspLogValue = aspLogValue.substring(0, aspLogValue.length() - joint.length());

长度确实是多减去一. 
可能作者疏忽了,也不算什么大的问题.
